### ISSUE TITLE
how to install plugin on ci?

### ISSUE THREAD

**Issue by landsman** [mhassan1/yarn-plugin-after-install#13]
Hey, first of all I want to thank you for this plugin! 

What I'm struggling with right now is this error:

```
Internal Error: Cannot find module '/home/runner/work/web-next/web-next/.yarn/plugins/@yarnpkg/plugin-after-install.cjs'
Require stack:
- /home/runner/.cache/node/corepack/yarn/3.5.1/yarn.js
Require stack:
- /home/runner/.cache/node/corepack/yarn/3.5.1/yarn.js
    at Function.Module._resolveFilename (node:internal/modules/cjs/loader:1028:15)
    at Function.Module._load (node:internal/modules/cjs/loader:873:27)
    at Module.require (node:internal/modules/cjs/loader:1100:19)
    at require2 (/opt/hostedtoolcache/node/16.20.1/x64/lib/node_modules/corepack/dist/corepack.js:41313:24)
    at l8 (/home/runner/.cache/node/corepack/yarn/3.5.1/yarn.js:390:12580)
    at mf (/home/runner/.cache/node/corepack/yarn/3.5.1/yarn.js:390:13423)
    at D (/home/runner/.cache/node/corepack/yarn/3.5.1/yarn.js:391:21744)
    at Function.find (/home/runner/.cache/node/corepack/yarn/3.5.1/yarn.js:391:22350)
    at async i (/home/runner/.cache/node/corepack/yarn/3.5.1/yarn.js:446:10705)
    at async t (/home/runner/.cache/node/corepack/yarn/3.5.1/yarn.js:446:10283
```

that I facing in GitHub Actions. From what I search it's probably because yarn is not able to automatically download the plugin if it's missing locally. Is that right?

`.yarnrc.yml` looks ordinary, it has generated these lines:

```yml
plugins:
  - path: .yarn/plugins/@yarnpkg/plugin-after-install.cjs
    spec: "https://raw.githubusercontent.com/mhassan1/yarn-plugin-after-install/v0.5.0/bundles/@yarnpkg/plugin-after-install.js"
```

---

- Yarn version: `3.5.1`
- Node version: `v16.19.1`

Can you recommend something? 🙏
